column:
  xugu:
    integer: integer
    int: int
    pls_integer: integer
    binary_integer: integer
    bigint: bigint
    longint: bigint
    long: bigint
    float: float
    binary_float: float
    double: double
    binary_double: double
    real: double
    tinyint: tinyint
    smallint: smallint
    short: smallint
    numeric: numeric
    decimal: numeric
    number: numeric
    char: char
    nchar: nchar
    varchar: varchar
    nvarchar: varchar
    nvarchar2: varchar
    varchar2: varchar
    clob: clob
    text: text
    nclob: nclob
    guid: guid
    boolean: boolean
    bool: bool
    blob: blob
    binary: binary
    raw: binary
    rowversion: rowversion
    timestamp: timestamp
    date: date
    datetime: datetime
    time: time
    interval: interval
  gbase8a:
    tinyint: tinyint
    smallint: smallint
    int: int
    bigint: bigint
    float: float
    double: double
    decimal: decimal
    numeric: numeric
    char: char
    varchar: varchar
    text: text
    blob: blob
    longblob: longblob
    date: date
    datetime: datetime
    time: time
    timestamp: timestamp
  cassandra:
    bigint: bigint
    blob: blob
    boolean: boolean
    counter: counter
    date: date
    decimal: decimal
    double: double
    float: float
    inet: inet
    int: int
    smallint: smallint
    text: text
    time: time
    timestamp: timestamp
    datetime: timestamp
    tinyint: tinyint
    uuid: uuid
    varchar: varchar
    varint: varint
    map: map
    set: set
    list: list
  postgresql:
    bigint: bigint
    int8: int8
    bigserial: bigserial
    serial8: serial8
    bit: bit
    boolean: boolean
    box: box
    bytea: bytea
    char: char
    varchar: varchar
    cidr: cidr
    circle: circle
    date: date
    double precision: double precision
    float8: float8
    inet: inet
    integer: integer
    json: json
    jsonb: jsonb
    line: line
    lseg: lseg
    macaddr: macaddr
    macaddr8: macaddr8
    money: money
    numeric: numeric
    decimal: decimal
    path: path
    pg_lsn: pg_lsn
    point: point
    polygon: polygon
    float4: float4
    smallint: smallint
    int2: int2
    smallserial: smallserial
    serial2: serial2
    serial: serial
    serial4: serial4
    text: text
    time: time
    timestamp: timestamp
    tsquery: tsquery
    tsvector: tsvector
    txid_snapshot: txid_snapshot
    uuid: uuid
    xml: xml
dclsql:
  xugu:
    createuser: "CREATE USER % IDENTIFIED BY '%'"
    updateaccount: "ALTER USER % IDENTIFIED BY '%'"
    deleteuser: "DROP USER %"
    lockuser: "ALTER USER % ACCOUNT LOCK"
    usernum: "SELECT COUNT(*) FROM DBA_USERS WHERE USER_NAME='%'"
    schemasnum: "SELECT COUNT(*) FROM DBA_SCHEMAS WHERE SCHEMA_NAME = '%'"
    addpermissions: "GRANT % ON %.% To %"
    deletepermissions: "REVOKE % ON %.% FROM %"
    createschemas: "CREATE SCHEMA % AUTHORIZATION %"
    dropschemas: "DROP SCHEMA %"
    author: "GRANT % ANY TABLE IN SCHEMA % TO %"
  gbase8a:
    createuser: "CREATE USER '%'@'%' IDENTIFIED BY '%'"
    updateaccount: "ALTER USER % IDENTIFIED BY '%'"
    deleteuser: "DROP USER %"
    deleteipuser: "DROP USER '%'@'%'"
    lockuser: "ALTER USER % ACCOUNT LOCK"
    usernum: "SELECT COUNT(*) FROM GBASE.USER WHERE USER='%'"
    schemasnum: "SELECT COUNT(*) FROM DBA_SCHEMAS WHERE SCHEMA_NAME = '%'"
    addpermissions: "GRANT % ON %.% To %"
    deletepermissions: "REVOKE % ON %.% FROM %"
    createschemas: "CREATE SCHEMA % AUTHORIZATION %"
    dropschemas: "DROP SCHEMA %"
    author: "GRANT % ANY TABLE IN SCHEMA % TO %"
databasename:
  xugu: xugu
  gbase8a: gbase8a
  cassandra: cassandra
  postgresql: postgresql
